### ISSUE TITLE
Warn when a particular link is out of date

### ISSUE THREAD

**Issue by vadi2** [Mudlet/deployment-link-probot#45]
When a PR has a successful build and a new one is added, there's a period when the links shown aren't really the latest ones. It's not obvious at all and requires manual comparison of commit IDs to find it out.

It would be nice if on a new commit, the bot mentioned that the link shown is out of date and a new one is coming, and removed that comment when the build is done.

It's a practical issue I run into so would be nice to get rid of the manual work!

**Comment by vadi2** [comment]
@keneanung what do you think?

**Comment by keneanung** [comment]
This might be relatively easy to do and if it is enough to help people out, I can't see a reason not to do this.
