### ISSUE TITLE
Show translation stats in translations PR

### ISSUE THREAD

**Issue by vadi2** [Mudlet/deployment-link-probot#9]
It would be really cool if the translation stats were pulled out of build logs and displayed right in the translation PR, so we don't have to dig for them (for example in https://github.com/Mudlet/Mudlet/pull/2546).

**Comment by keneanung** [comment]
How do you want it to look like? Which stats are of interest?

**Comment by vadi2** [comment]
I'd say the `lang`, `trnsl`, `utrnsl`, and the `percentage` columns, with your choice of formatting?

@Kebap

**Comment by Kebap** [comment]
Here's the raw data for comparison:

```
lang	trnsl	utrnsl	finish	unfin	total	percentage
de_DE	1896	45	1896	0	1941	97
el_GR	0	1941	0	0	1941	0
en_GB	411	1530	406	5	1941	21
es_ES	744	1197	744	0	1941	38
fr_FR	200	1741	200	0	1941	10
it_IT	1542	399	1542	0	1941	79
nl_NL	46	1895	46	0	1941	2
pl_PL	516	1425	516	0	1941	26
pt_PT	262	1679	262	0	1941	13
ru_RU	1749	192	1747	2	1941	90
zh_CN	1005	936	1005	0	1941	51
zh_TW	0	1941	0	0	1941	0
en_US	11	0	11	0	11	100
```

**Comment by keneanung** [comment]
What do you guys think about https://github.com/Mudlet/Mudlet/pull/2566#issuecomment-495540858 ?

**Comment by vadi2** [comment]
It looks very neat, but I think it would be better if it just appeared on Crowdin's translation PR (so match by title) as-is without needing to be expanded, so people have a better chance of finding it. I'm not sure of showing the translation stats in other PRs either.

**Comment by keneanung** [comment]
Hm, okay I'll try to come up with something

**Comment by keneanung** [comment]
So, how about https://github.com/Mudlet/Mudlet/pull/2579#issuecomment-496677438 ? I added headings (mainly to make it easier to replace the right thing) as well

**Comment by vadi2** [comment]
Looks great :)

**Comment by Kebap** [comment]
Numbers were updated in PR after work in Crowdin, commit, build finished. :+1:
